#hikari.maximum-pool-size: 4
#url: jdbc:postgresql://ec2-52-86-115-245.compute-1.amazonaws.com/d2p70ft1bv6u4c
#username: sohthnduwbipay
#password: 62971a3ff89fb0c590e0253d6871ba2256d678d39233dfd9f41a91eff1ea0246
#platform: postgres
#driver-class-name: org.postgresql.Driver
#


---
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sns
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret-key: i_love_benchpress+latpulldown_deadlift_squat_machinepress_militaryPress_andYou

  token:
      expired-time-ms: 2592000000